### ISSUE TITLE
db:seed is throwing an error when run locally

### ISSUE THREAD

**Issue by breyerjs** [season89757/cosi166-learncoding#9]
db:seed is throwing an error when run locally. For local dev, should I use different seeds?
I attached a screenshot below. 

![image](https://cloud.githubusercontent.com/assets/5419342/14183378/024a26ac-f73e-11e5-8339-7c19dd2b4a70.png)

**Comment by anboi1225** [comment]
Mine just work fine as the following shows,
![screenshot from 2016-03-31 13 52 54](https://cloud.githubusercontent.com/assets/15203243/14185525/402d6fe2-f748-11e5-82c5-0ebfddaa7564.png)

But it make sense though since the error said: certificate verify failed, I don't assign the google API key while sending the search request to the server. But it seems that key is optional not necessary. I will check it out.

**Comment by breyerjs** [comment]
Awesome, thanks!

**Comment by anboi1225** [comment]
Hi, Jackson, now the code should work. just pull the newest version then it will work.

require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

we just add those two lines.

**Comment by breyerjs** [comment]
Awesome, that's great, thanks! Much appreciated.

I've gotten some good work done on forums--should have a minimal version in the next day or two.
